<template>
    <div>
        <h2>スキル</h2>
        <h3>学習言語</h3>
        <ul>
            <li>JavaScript</li>
            <li>PHP</li>
        </ul>
        <p>他にも、マークアップ言語のHTMLやスタイルシート言語のCSSも学習しました。</p><br>
        <h3>主な使用言語・フレームワーク・ライブラリ</h3>
        <ul>
            <li>JavaScript</li>
            <li>Vue.js</li>
            <li>React</li>
        </ul>
    </div>
</template>
